export const LOADED_ALL_CHILDREN= 'LOAD_ALL_CHILDREN';
export const LOADED_SINGLE_CHILD= 'LOADED_SINGLE_CHILD';
export const SAVED_CHILD= 'SAVED_CHILD';
export const UPDATED_CHILD= 'UPDATED_CHILD';
export const DELETE_CHILD= 'DELETE_CHILD';
export const LOADED_PROFILE= 'LOADED_PROFILE';
export const SAVED_PROFILE= 'SAVED_PROFILE';
